ApniShopWebAssignment/Controllers/ProductController.cs
using ApniShopWebAssignment.Controllers;
using ApniShopWebAssignment.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using Microsoft.Build.Framework;
using Microsoft.Extensions.Logging;

namespace ApniShopWebAssignment.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                var products = DBMODEL.PTables.SqlQuery("SELECT TOP(1000) [PID],[PName],[PImage],[PCategory],[PRating], [PPrice],[PWish],[PQuantity],[popularity] FROM [dbo].[PTable] ").ToList<PTable>();
                return View(products);
            }
        }




        // GET: ProductTable
        public ActionResult ViewProduct()
        {
            return View();
        }
        public ActionResult AddProduct()
        {
            PTable tableModel = new PTable();
            return View(tableModel);
        }

        [HttpPost]
        public ActionResult AddProduct(PTable tableModel)
        {
            string filename = Path.GetFileNameWithoutExtension(tableModel.ImageFile.FileName);
            string extension = Path.GetExtension(tableModel.ImageFile.FileName);
            filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
            tableModel.PImage = "~/Image/" + filename;
            filename = Path.Combine(Server.MapPath("~/Image/"), filename);
            tableModel.ImageFile.SaveAs(filename);
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                if (DBMODEL.PTables.Any(x => x.PName == tableModel.PName))
                {
                    ViewBag.ErrorMessage = "Product Already Exists";
                    return View("AddProduct", new PTable());
                }

                DBMODEL.PTables.Add(tableModel);
                DBMODEL.SaveChanges();
            }

            ModelState.Clear();
            ViewBag.SuccessMessage = "Product Addition Successful";
            return View("AddProduct", new PTable());


        }
        public ActionResult AddProductToTempDatabase()
        {
            UPTable entry = new UPTable();
            return View(entry);
        }

        [HttpPost]
        public ActionResult AddProductToTempDatabase(UPTable tableModel)
        {
            string filename = Path.GetFileNameWithoutExtension(tableModel.ImageFile.FileName);
            string extension = Path.GetExtension(tableModel.ImageFile.FileName);
            filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
            tableModel.UPImage = "~/Image/" + filename;
            filename = Path.Combine(Server.MapPath("~/Image/"), filename);
            tableModel.ImageFile.SaveAs(filename);

            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                if (DBMODEL.UPTables.Any(x => x.UPNAME == tableModel.UPNAME))
                {
                    ViewBag.ErrorMessage = "Product Already Exists In Database";
                    return View("AddProductToTempDatabase", new UPTable());
                }

                DBMODEL.UPTables.Add(tableModel);
                DBMODEL.SaveChanges();
            }

            ModelState.Clear();
            ViewBag.SuccessMessage = "Product Addition Successful";
            return View("AddProductToTempDatabase", new UPTable());
        }








        public ActionResult OrderNow(int id)
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                Session["PQTY"] = id;
                UTable entry = Session["DATA"] as UTable;
                OTable neworder = new OTable();
                neworder.CustomerID = entry.UID;
                neworder.ShippingServiceName = "TCS";
                neworder.OrderStatus = "Generated";
                neworder.OrderCountry = "Pakistan";
                neworder.OrderDate = DateTime.Now.Date;
                neworder.ProductID = id;
                return View(neworder);
            }
        }
        public ActionResult SaveOrderDetails()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveOrderDetails(OTable oTable)
        {

            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                var id = Session["PQTY"];
                int id2 = (int)id;
                if (DBMODEL.PTables.Any(newentry => newentry.PID == id2))
                {
                    ApniShopWebAssignment.Models.PTable entry = DBMODEL.PTables.SingleOrDefault(x => x.PID == id2);
                    var removeid = DBMODEL.PTables.Find(entry.PID);
                    DBMODEL.PTables.Remove(removeid);
                    DBMODEL.SaveChanges();
                    entry.PQuantity = entry.PQuantity - 1;
                    entry.popularity = entry.popularity + 1;
                    DBMODEL.PTables.Add(entry);
                    DBMODEL.SaveChanges();
                }
                if (DBMODEL.OTables.Any(x => x.OrderID == oTable.OrderID))
                {
                    ViewBag.ErrorMessage = "Order Already Exists";
                    return View("SaveOrderDetails", new OTable());
                }
                DBMODEL.OTables.Add(oTable);
                DBMODEL.SaveChanges();

            }

            ModelState.Clear();
            ViewBag.SuccessMessage = "Order Has Been Generated ";
            return View("SaveOrderDetails", oTable);
        }

        public ActionResult ApproveProduct(UPTable tablemodel)
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                return View();
            }
        }

        public ActionResult WishList(int id)
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                if (DBMODEL.PTables.Any(newentry => newentry.PID == id))
                {
                    ApniShopWebAssignment.Models.PTable entry = DBMODEL.PTables.SingleOrDefault(x => x.PID == id);
                    var removeid = DBMODEL.PTables.Find(entry.PID);
                    DBMODEL.PTables.Remove(removeid);
                    DBMODEL.SaveChanges();
                    int val= (int)entry.PWish.GetValueOrDefault() + 1;
                    entry.PWish = val;
                    DBMODEL.PTables.Add(entry);
                    DBMODEL.SaveChanges();
                }
            }
            return View();

        }

        public ActionResult WishListRemove(int id)
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                if (DBMODEL.PTables.Any(newentry => newentry.PID == id))
                {
                    ApniShopWebAssignment.Models.PTable entry = DBMODEL.PTables.SingleOrDefault(x => x.PID == id);
                    var removeid = DBMODEL.PTables.Find(entry.PID);
                    DBMODEL.PTables.Remove(removeid);
                    DBMODEL.SaveChanges();
                    int val = (int)entry.PWish.GetValueOrDefault() - 1;
                    entry.PWish = val;
                    DBMODEL.PTables.Add(entry);
                    DBMODEL.SaveChanges();
                }
            }
            return View();
        }



    }
}

ApniShopWebAssignment/Controllers/UTableController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ApniShopWebAssignment.Models;

namespace ApniShopWebAssignment.Controllers
{
    public class UTableController : Controller
    {
        public static bool isLoggedIndex=false;

        [HttpGet]
        public ActionResult Registration()
        {
            UTable tablemodel = new UTable();
            return View(tablemodel);
        }
        // GET: Table
        [HttpPost]
        public ActionResult Registration(UTable tableModel)
        {
            string filename = Path.GetFileNameWithoutExtension(tableModel.ImageFile.FileName);
            string extension = Path.GetExtension(tableModel.ImageFile.FileName);
            filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
            tableModel.UProfilePicturePath = "~/Image/" + filename;
            filename = Path.Combine(Server.MapPath("~/Image/"), filename);
            tableModel.ImageFile.SaveAs(filename);
            using (LoginRegisterDatabaseEntities2 NEWDBMODEL = new LoginRegisterDatabaseEntities2())
            {
                if (ModelState.IsValid)
                {
                    if (NEWDBMODEL.UTables.Any(x => x.Uname == tableModel.Uname))
                    {
                        ViewBag.ErrorMessage = "UserName Already Exists";
                        return View("Registration", new UTable());
                    }
                    NEWDBMODEL.UTables.Add(tableModel);
                    NEWDBMODEL.SaveChanges();
                }
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Registration Successful";
            return View("Registration", new UTable());
        }
        [HttpGet]
        public ActionResult Login()
        {
            UTable tablemodel = new UTable();
            return View(tablemodel);
        }
        [HttpPost]
        public ActionResult Login(UTable tableModel)
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                if( (DBMODEL.UTables.Any(x=>x.Uname==tableModel.Uname)) && (DBMODEL.UTables.Any(x => x.UPassword == tableModel.UPassword)))
                {
                    ApniShopWebAssignment.Models.UTable check = DBMODEL.UTables.Single(x => x.Uname == tableModel.Uname);
                    if (tableModel.UIsAdmin==true)
                    {
                     
                        if(check.UIsAdmin==tableModel.UIsAdmin)
                        {
                            ModelState.Clear();
                            return RedirectToActionPermanent("AdminIndex");
                        }
                        else
                        {
                            UTable newentry = new UTable();
                            ViewBag.ErrorMessage = "YOU ARE NOT AN ADMIN!!!";
                            return View();

                        }
                    }
                    else
                    {
                        ModelState.Clear();
                        isLoggedIndex = true;
                        ApniShopWebAssignment.Models.UTable entry = DBMODEL.UTables.Single(x => x.Uname == tableModel.Uname);
                        Session["DATA"] = entry;
                        return RedirectToActionPermanent("Index", entry);
                    }

                    
                }
                else
                {
                    ModelState.Clear();
                    ViewBag.ErrorMessage = "Login Credentials Are Incorrect";
                    return View();
                }
        
            }
        
        }

        public ActionResult Index()
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                var entry = DBMODEL.PTables.Where(x => x.popularity >= 5).ToList();
                return View(entry);
            }
        }

        public ActionResult AdminIndex()
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                var products = DBMODEL.UPTables.SqlQuery("SELECT TOP(1000) [UPID],[UPNAME],[UPImage],[UPCategory],[UPRating], [UPPrice],[UPWish],[UPQuantity] FROM [dbo].[UPTable] ").ToList<UPTable>();
                return View(products);
            }
        }

        public ActionResult ForgotPassword()
        {
            UTable tablemodel = new UTable();
            return View(tablemodel);
        }
        [HttpPost]
        public ActionResult ForgotPassword(UTable tableModel)
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                if ((DBMODEL.UTables.Any(x => x.Uname == tableModel.Uname)))
                {
                    ApniShopWebAssignment.Models.UTable entry = DBMODEL.UTables.Single(x => x.Uname == tableModel.Uname);
                    return View("ShowUserName",entry);
             
                }
                else
                {
                    ModelState.Clear();
                    ViewBag.ErrorMessage = "UserName Does Not Exist";
                    return View();
                }

            }

        }
        public ActionResult ProfilePage(UTable tablemodel)
        {
            if (isLoggedIndex)
            {
                var data = Session["DATA"] as UTable;
                return View(data); 
            }
            else
            {
                return View(tablemodel);
            }
        }

        public ActionResult EditProfile()
        {
            var user = Session["DATA"] as UTable;

            return View(user);
        }

        [HttpPost]
        public ActionResult EditProfile(UTable tableModel)
        {
            string filename = Path.GetFileNameWithoutExtension(tableModel.UProfilePicturePath);
            string extension = Path.GetExtension(tableModel.ImageFile.FileName);
            filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
            tableModel.UProfilePicturePath = "~/Image/" + filename;
            filename = Path.Combine(Server.MapPath("~/Image/"), filename);
            tableModel.ImageFile.SaveAs(filename);

            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                var entry = Session["DATA"] as UTable;

                DBMODEL.UTables.Remove(DBMODEL.UTables.Find(entry.UID));
                DBMODEL.SaveChanges();

                DBMODEL.UTables.Add(tableModel);
                DBMODEL.SaveChanges();
            }
            ModelState.Clear();
            return View("ProfilePage", tableModel);
        }

        public ActionResult AddProductToProductDatabase(int id,string id2)
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                ApniShopWebAssignment.Models.UPTable check = DBMODEL.UPTables.Single(x => x.UPNAME == id2);
                PTable newentry = new PTable();
                newentry.PName = check.UPNAME;
                newentry.PQuantity = check.UPQuantity;
                newentry.PPrice = check.UPPrice;
                newentry.PRating = check.UPRating;
                newentry.PWish = check.UPWish;
                newentry.PImage = check.UPImage;
                newentry.ImageFile = check.ImageFile;
                newentry.PCategory = check.UPCategory;
                DBMODEL.PTables.Add(newentry);
                _ = DBMODEL.SaveChanges();
                var removeid = DBMODEL.UPTables.Find(id);
                DBMODEL.UPTables.Remove(removeid);
                _ = DBMODEL.SaveChanges();
                return View();
            }
        }
        public ActionResult RemoveProductFromTempDatabase(int id)
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                var removeid = DBMODEL.UPTables.Find(id);
                DBMODEL.UPTables.Remove(removeid);
                _ = DBMODEL.SaveChanges();
                return View();
            }
        }
        public ActionResult userOrders(int id)
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                  var entry = DBMODEL.OTables.Where(x => x.CustomerID == id).ToList();

                return View(entry);
            }
        }

        public ActionResult GiveRating(int id)
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                var current = DBMODEL.OTables.Find(id);
                return View(current);
            }
        }

        [HttpPost]
        public ActionResult GiveRating(OTable tableModel)
        {
            using (LoginRegisterDatabaseEntities2 DBMODEL = new LoginRegisterDatabaseEntities2())
            {
                DBMODEL.OTables.Remove(DBMODEL.OTables.Find(tableModel.OrderID));
                DBMODEL.OTables.Add(tableModel);
                var entry = DBMODEL.OTables.Where(x => x.ProductID == tableModel.ProductID).ToList();
                DBMODEL.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Rating Updated";
            return View(tableModel);
        }

    }


}

ApniShopWebAssignment/Views/UTable/AddProductToProductDatabase.cshtml
@using System.Web;
@model IEnumerable<ApniShopWebAssignment.Models.UPTable>

@{
    ViewBag.Title = "AddProductToProductDatabase";
}

<h2>THE ITEM HAS BEEN APPROVED BY ADMIN</h2>

@Html.ActionLink("Back To Approvals", "AdminIndex", "UTable")

ApniShopWebAssignment/Views/UTable/AdminIndex.cshtml
@model IEnumerable<ApniShopWebAssignment.Models.UPTable>

@{
    ViewBag.Title = "AdminIndex";
}

<br />
<br />

<div class="row" style="margin: auto;
        width: 80%;
        height: 80%;
        border: 10px solid rgb(128, 0, 128);
        padding: 10px;
        background: white;
        font-family: 'Public Sans', sans-serif;
">

    <label class="label-success">@ViewBag.SuccessMessage</label>
    <table class="table">
        <tr>
            <th>
                Product ID
            </th>
            <th>
                Product Name
            </th>
            <th>
                Product Image
            </th>
            <th>
                Category
            </th>
            <th>
                Price
            </th>
            <th>
                Wishlist
            </th>
            <th>
                Quantity
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UPID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UPNAME)
                </td>
                <td>
                    <img src="@Url.Content(item.UPImage)" width="250" height="250" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UPCategory)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UPRating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UPPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UPWish)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UPQuantity)
                </td>
                <td>
                    @Html.ActionLink("Approve", "AddProductToProductDatabase", "UTable", new { id = item.UPID, id2 = item.UPNAME }, null)|
                    @Html.ActionLink("Not Approve", "RemoveProductFromTempDatabase", "UTable", new { id = item.UPID }, null)|

                </td>

            </tr>
        }

    </table>
</div>

ApniShopWebAssignment/Views/UTable/EditProfile.cshtml
@model ApniShopWebAssignment.Models.UTable

@{
    ViewBag.Title = "EditProfile";
}

<br />
<br />

<div class="row" style="        margin: auto;
        width: 40%;
        border: 10px solid rgb(128, 0, 128);
        padding: 10px;
        background: white;
        font-family: 'Public Sans', sans-serif;
">
    <div style="margin: auto; width: 50%; padding: 10px; ">
        <div class="card">
            <div class="card-header">
                <h2 style="text-align: center;">Edit Profile</h2>
                <br>
            </div>

            <div class="card-body">
                @using (Html.BeginForm("EditProfile", "UTable", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr style="border: 1px solid black;" />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        User ID
                        @Html.EditorFor(model => model.UID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UID, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        Username
                        @Html.EditorFor(model => model.Uname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Uname, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        Password
                        @Html.EditorFor(model => model.UPassword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UPassword, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        Are you an Admin(Yes/No)?
                        @Html.EditorFor(model => model.UIsAdmin, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UIsAdmin, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        Gender
                        @Html.EditorFor(model => model.UGender, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UGender, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        Birthday
                        @Html.EditorFor(model => model.UBirthday, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UBirthday, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        Current Address
                        @Html.EditorFor(model => model.UAddress, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UAddress, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        Mobile No(+)
                        @Html.EditorFor(model => model.UMobileNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UMobileNo, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.UProfilePicturePath, htmlAttributes: new { @class = "control-label col-md-2" })
                        <input type="file" name="ImageFile" required>
                        @Html.ValidationMessageFor(model => model.UProfilePicturePath, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group" style="text-align: center;">
                        <input type="submit" value="Edit" class="btn btn-primary btn-lg" />
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
</div>

<style>
    .form-control {
        border: 0px none;
    }
</style>

ApniShopWebAssignment/Views/UTable/ForgotPassword.cshtml
@model ApniShopWebAssignment.Models.UTable

@{
    ViewBag.Title = "ForgotPassword";
}

<br />
<br />
<head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@100&display=swap" rel="stylesheet">
</head>
<div class="row" style="        margin: auto;
        width: 40%;
        border: 10px solid rgb(128, 0, 128);
        padding: 10px;
        background: white;
        font-family: 'Public Sans', sans-serif;
">
    <div style="margin: auto; width: 50%; padding: 10px; ">
        <div class="card">
            <div class="card-header">
                <h3 style="text-align:center;">Forgot Password</h3>
            </div>

            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group" style ="text-align: center;">
                            <h4>Please Enter Your UserName</h4>
                            @Html.EditorFor(model => model.Uname, new { htmlAttributes = new { @class = "form-control field" } })
                            @Html.ValidationMessageFor(model => model.Uname, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group" style ="text-align: center;">
                            <input type="submit" value="Submit" class="btn btn-primary btn-lg" />
                        </div>

                        <div class="form-group" style ="text-align: center;">
                            <label class="label-danger">@ViewBag.ErrorMessage</label>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ApniShopWebAssignment/Views/UTable/Index.cshtml
@model IEnumerable<ApniShopWebAssignment.Models.PTable>
@using ApniShopWebAssignment.Models;
@{
    ViewBag.Title = "Index";
}

<br />
<br />

<div class="row" style="margin: auto;
        width: 80%;
        height: 80%;
        border: 10px solid rgb(128, 0, 128);
        padding: 10px;
        background: white;
        font-family: 'Public Sans', sans-serif;
">

    <h2>Index</h2>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PWish)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PQuantity)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PID)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.PName)
                </td>
                <td>
                    <img src="@Url.Content(item.PImage)" width="50" height="50" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PWish)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PQuantity)
                </td>
                <td>
                    @Html.ActionLink("Order Now", "OrderNow", "Product", new { id = item.PID }, new { @class = "ui-btn" })
                </td>
            </tr>

        }
    </table>

    <div class="new-button-group" style="position: absolute; left: 600px; top: 385px;">
        @Html.ActionLink("Order Products", "Index", "Product", null, new { @class = "btn btn-primary btn-lg" })
        @Html.ActionLink("Request Selling Product", "AddProductToTempDatabase", "Product", new UPTable(), new { @class = "btn btn-primary btn-lg" })
    </div>
</div>

ApniShopWebAssignment/Views/UTable/Login.cshtml
@model ApniShopWebAssignment.Models.UTable

@{
    ViewBag.Title = "Login";
}

<br />
<br />

<div class="row" style="        margin: auto;
        width: 40%;
        border: 10px solid rgb(128, 0, 128);
        padding: 10px;
        background: white;
        font-family: 'Public Sans', sans-serif;
">
    <div style="margin: auto; width: 50%; padding: 10px; ">
        <div class="card">
            <div class="card-header">
                <h2  style ="text-align: center;">User Login</h2>
                <br>
            </div>

            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group" style ="text-align: center;">
                        <h4>UserName </h4>
                        @Html.EditorFor(model => model.Uname, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Uname, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group" style="text-align: center;">
                        <h4>Password </h4>
                        @Html.EditorFor(model => model.UPassword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UPassword, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group" style="text-align: center;">
                        <h4>Are You An Admin? </h4>
                        @Html.EditorFor(model => model.UIsAdmin, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UIsAdmin, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group"  style ="text-align: center;">
                        <input type="submit" value="Login" class="btn btn-primary btn-lg" />
                    </div>

                    <div class="form-group"  style ="text-align: center;">
                        <label class="label-danger">@ViewBag.ErrorMessage</label>
                    </div>

                    <div class="form-group"  style ="text-align: center;">
                        <h5>NOT ALREADY A MEMBER?</h5>
                        <h5 style="align-items:center;">@Html.ActionLink("SignUp", "Registration", "UTable")</h5>

                    </div>
                }
            </div>
        </div>
    </div>
</div>


<style>
    .form-control {
        border: 0px none;
    }

</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}